const WEB_SOCKET_CONNECT = 'WEB_SOCKET_CONNECT';
const WEB_SOCKET_SEND = 'WEB_SOCKET_SEND';
const WEB_SOCKET_DISCONNECT = 'WEB_SOCKET_DISCONNECT';
const WEB_SOCKET_MESSAGE = 'WEB_SOCKET_MESSAGE';

export { WEB_SOCKET_CONNECT, WEB_SOCKET_SEND, WEB_SOCKET_DISCONNECT, WEB_SOCKET_MESSAGE };
