const FETCH_ALL_COMMENTS = 'FETCH_ALL_COMMENTS';
const ALL_COMMENTS = 'ALL_COMMENTS';
const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';

export { FETCH_ALL_COMMENTS, ALL_COMMENTS, ADD_COMMENT_REQUEST };
